lzc-sdk-version: "0.1"
name: CommaFeed
package: cloud.lazycat.app.commafeed
version: 5.10.0
description: 受Google Reader 启发的RSS阅读器
homepage: https://github.com/Athou/commafeed
author: Athou
application:
  subdomain: commafeed
  background_task: true
  public_path:
    - /
  routes:
    - /=http://commafeed:8082/
services:
  commafeed:
    image: registry.lazycat.cloud/czyt/athou/commafeed:25602cd411a307e7
    binds:
      - /lzcapp/var/data:/commafeed/data
