name: CommaFeed
package: cloud.lazycat.app.commafeed
version: 5.11.1
min_os_version: 1.3.8
homepage: https://github.com/Athou/commafeed
author: Athou
application:
  subdomain: commafeed
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://commafeed:8082/
services:
  commafeed:
    # athou/commafeed:5.11.1-h2-jvm
    image: registry.lazycat.cloud/czyt/athou/commafeed:b374eefdf8b3bfa9
    binds:
      - /lzcapp/var/data:/commafeed/data

locales:
  zh:
    name: CommaFeed
    description: 受 Google Reader 启发的自托管个人 RSS 阅读器。
  en:
    name: CommaFeed
    description: Google Reader inspired self-hosted personal RSS reader.
